---
- name: Complete system provisioning
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: "run apt-get update"
    apt:
        update_cache: yes
        cache_valid_time: 3600

  - name: "run aptitude safe-upgrade"
    apt:
      upgrade: yes
  - name: package installation
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: present
